version: '2'
services:
    db:
        image: mariadb:5.5
        environment:
          MYSQL_ROOT_PASSWORD: 'cakephp'
          MYSQL_DATABASE: 'cakephp'
        ports:
            - "3306:3306"
    php:
        image: travisrowland/dockercakephp_php:latest
        expose:
            - "9000"
        volumes_from:
            - cakephp
        volumes:
            - /www/logs:/var/log/cakephp
        links:
            - db
            - cakephp
        environment:
          DEBUG: 'true'
          DB_HOST: 'db' # Leave this as 'db' to utilize MySQL container(s)
          DB_USERNAME: 'root'
          DB_PASSWORD: 'cakephp'
          DB_DATABASE: 'cakephp'
          DB_SEED: 'DatabaseSeed'
          EMAIL_HOST: 'smtp.mandrillapp.com'
          EMAIL_PORT: '587'
          EMAIL_TIMEOUT: '30'
          EMAIL_USERNAME: 'support@dynamictivity.com'
          EMAIL_PASSWORD: '2CpbYjFX9NUbRjUVzvu8hw' # Test key, replace with your own
          EMAIL_TLS: 'True'
          DYN_SITE_URL: 'http://localhost:8080'
          DYN_SITE_NAME: 'Foundation App'
          DYN_GOOGLE_ANALYTICS: 'UA-5187184-35'
    cakephp:
        # image: travisrowland/foundation-app
        build: .
        volumes:
            - /www
    nginx:
        image: travisrowland/dockercakephp_nginx
        ports:
            - "80:80"
        links:
            - php
            - cakephp
        volumes_from:
            - cakephp
        volumes:
            - ./logs/nginx/:/var/log/nginx
